version: 2
jobs:
  build:
    docker: # use the docker executor type; machine and macos executors are also supported
      - image: circleci/node:8.9.4 # the primary container, where your job's commands are run
    steps:
      # Check out the code from Github
      - checkout

      # Install dependencies
      - run:
          name: Install deps
          command: npm install

      # Checks if project can build successfully
      - run:
          name: Build project
          command: npm run build
  unit-tests:
    docker: # use the docker executor type; machine and macos executors are also supported
      - image: circleci/node:8.9.4 # the primary container, where your job's commands are run
    steps:
      # Check out the code from Github
      - checkout

      # Install dependencies
      - run:
          name: Install deps
          command: npm install

      # Checks if unit tests are passing
      - run:
          name: Run Unit Tests
          command: npm run test:unit


workflows:
  version: 2
  build-test:
    jobs:
      - build
      - unit-tests
          requires:
            - build